/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Localizar_Arquivo_Controller;
import Controller.Pessoas_Controller;
import Model.Pessoas_Model;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rh
 */
public class Form_Lancar_Prest extends javax.swing.JDialog {

    private String localArquivoSelecionado;
    private List<Pessoas_Model> prestadorNaoCadastrados = new ArrayList<>();

    /**
     * Creates new form Form_Lancar_Prest
     */
    public Form_Lancar_Prest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Form_Lancar_Prest(java.awt.Frame parent, boolean modal, List<Pessoas_Model> listaPrestador, String caminhoArquivo) {
        super(parent, modal);
        this.prestadorNaoCadastrados = listaPrestador;
        this.localArquivoSelecionado = caminhoArquivo;
        initComponents();
        preencherAreaPrestadoresNaoCadastrados();
    }

    /**
     * Preenche a area com os prestadores não cadastrados
     */
    private void preencherAreaPrestadoresNaoCadastrados() {

        for (Pessoas_Model prestadorNaoCadastrado : prestadorNaoCadastrados) {
            textAreaPrestNotCadastrado.append("PIS                NOME\n");
            textAreaPrestNotCadastrado.append(prestadorNaoCadastrado.getPisPasep() + "   " + prestadorNaoCadastrado.getNome_pessoa() + "\n\n");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInserirPrestadores = new javax.swing.JButton();
        btnNaoInserir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPrestNotCadastrado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensagem:");

        jLabel2.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Os prestador(es) abaixo descriminado, não foram possuem cadastro nesta base de dados. ");

        jLabel3.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Confirma a inclusão dos mesmos a base de dados?");

        btnInserirPrestadores.setText("SIM, INSERIR NA BASE");
        btnInserirPrestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPrestadoresActionPerformed(evt);
            }
        });

        btnNaoInserir.setText("NÃO INSERIR");
        btnNaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserirPrestadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNaoInserir))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirPrestadores)
                    .addComponent(btnNaoInserir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textAreaPrestNotCadastrado.setColumns(20);
        textAreaPrestNotCadastrado.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        textAreaPrestNotCadastrado.setRows(5);
        jScrollPane1.setViewportView(textAreaPrestNotCadastrado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirPrestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPrestadoresActionPerformed
        Pessoas_Controller control = new Pessoas_Controller();
        // passamos a lista de prestadores que não estão na base de dados para inserção
        // capturamos o retorno, indicando q todos estão inseridos
        boolean retorno = control.gravar_Novo_Prestador(prestadorNaoCadastrados);

        if (retorno) {
            // lê novamente o arquivo escolhido pelo usuario, apos os prestadores serem inseridos na base
            Localizar_Arquivo_Controller lerArquivo = new Localizar_Arquivo_Controller();
            List<String> linhas = lerArquivo.lerArquivoSelecionado(localArquivoSelecionado);

            // recuperar a lista dos prestadores que ESTÃO CADASTRADOS e passa para a view que ira
            // capturar os valores de cada prestador
            Pessoas_Controller pessoas = new Pessoas_Controller();
            pessoas.buscarPisPasepBaseDados(linhas, localArquivoSelecionado);
            
            // fecha este formulario
            dispose();
        }
    }//GEN-LAST:event_btnInserirPrestadoresActionPerformed

    private void btnNaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoInserirActionPerformed
        dispose();
    }//GEN-LAST:event_btnNaoInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Lancar_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Lancar_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Lancar_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Lancar_Prest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Lancar_Prest dialog = new Form_Lancar_Prest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirPrestadores;
    private javax.swing.JButton btnNaoInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaPrestNotCadastrado;
    // End of variables declaration//GEN-END:variables
}
