/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Servicos_Controller;
import Model.Tbela_Consultar_Model;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jederson Andre
 */
public class Form_consulta extends javax.swing.JFrame {

    Tbela_Consultar_Model modelo = new Tbela_Consultar_Model();
    private static int idLanc = 0;

    /**
     * Creates new form Form_relatorio
     */
    public Form_consulta() {
        initComponents();
        tabelaResultado.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo_competencia = new javax.swing.JFormattedTextField();
        btn_selecionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        btn_alterar_lancamento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Competencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Competencia:");

        try {
            campo_competencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_competencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_competenciaKeyPressed(evt);
            }
        });

        btn_selecionar.setText("Selecionar");
        btn_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarActionPerformed(evt);
            }
        });
        btn_selecionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_selecionarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_competencia, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btn_selecionar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_competencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compt.", "Prestador", "Fonte", "Salario base", "INSS retido", "INSS patronal", "Lotacao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaResultadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaResultado);
        if (tabelaResultado.getColumnModel().getColumnCount() > 0) {
            tabelaResultado.getColumnModel().getColumn(0).setMinWidth(80);
            tabelaResultado.getColumnModel().getColumn(0).setMaxWidth(120);
            tabelaResultado.getColumnModel().getColumn(1).setMinWidth(120);
            tabelaResultado.getColumnModel().getColumn(1).setMaxWidth(200);
            tabelaResultado.getColumnModel().getColumn(2).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(2).setMaxWidth(120);
            tabelaResultado.getColumnModel().getColumn(3).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(3).setMaxWidth(120);
            tabelaResultado.getColumnModel().getColumn(4).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(4).setMaxWidth(120);
            tabelaResultado.getColumnModel().getColumn(5).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(5).setMaxWidth(120);
            tabelaResultado.getColumnModel().getColumn(6).setMinWidth(120);
            tabelaResultado.getColumnModel().getColumn(6).setMaxWidth(200);
        }

        btn_alterar_lancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_alterar.png"))); // NOI18N
        btn_alterar_lancamento.setText("Alterar");
        btn_alterar_lancamento.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_alterar_lancamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_alterar_lancamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_alterar_lancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_lancamentoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_deletar.png"))); // NOI18N
        jButton1.setText("Deletar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btn_alterar_lancamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alterar_lancamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarActionPerformed

        if (campo_competencia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "A competencia não pode ser vazia!");
        } else {
            String competencia = campo_competencia.getText();

            Servicos_Controller control = new Servicos_Controller();
            control.consultarLancamentoServicos(competencia, modelo);
        }
    }//GEN-LAST:event_btn_selecionarActionPerformed

    private void campo_competenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_competenciaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_selecionar.requestFocus();
        }
    }//GEN-LAST:event_campo_competenciaKeyPressed

    private void btn_selecionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_selecionarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (campo_competencia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "A competencia não pode ser vazia!");
            } else {
                String competencia = campo_competencia.getText();
                Servicos_Controller control = new Servicos_Controller();
                control.consultarLancamentoServicos(competencia, modelo);
            }
        }
    }//GEN-LAST:event_btn_selecionarKeyPressed

    private void btn_alterar_lancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_lancamentoActionPerformed
        // verifica se o id foi selecionado
        if (idLanc != 0) {
            String compt = campo_competencia.getText();
            Form_Lanc_Servicos form = new Form_Lanc_Servicos(this, rootPaneCheckingEnabled, compt, idLanc);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btn_alterar_lancamentoActionPerformed

    private void tabelaResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaResultadoMouseClicked
        // recupera o codigo(id) do lançamento
        int linha = tabelaResultado.getSelectedRow();
        idLanc = Integer.parseInt(tabelaResultado.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_tabelaResultadoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // exlui o registro selecionado na tabela
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente exluir o registro selecionado", "Mensagem", JOptionPane.YES_NO_OPTION) == 0) {
            Servicos_Controller del = new Servicos_Controller();
           int confirmacao = del.excluirRegistro(idLanc);
           
           if(confirmacao != 0){
               JOptionPane.showMessageDialog(null, "Registro foi exluido com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
           }
        } 

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar_lancamento;
    private javax.swing.JButton btn_selecionar;
    private javax.swing.JFormattedTextField campo_competencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaResultado;
    // End of variables declaration//GEN-END:variables
}
